site_name: pybind11-geobuf
site_url: https://pybind11-geobuf.readthedocs.io
site_description:  A compact binary encoding for geographic data, with python binding.
site_author: district10

repo_url: https://github.com/cubao/pybind11-geobuf
edit_uri: blob/master/docs/

theme: readthedocs
nav:
    - Home: index.md
    - About:
        - Release Notes: about/release-notes.md
        - License: about/license.md

plugins:
  - include-markdown

copyright: Copyright &copy; 2023 <a href="https://github.com/cubao">cubao team</a>.
